[package]
name = "hyparview"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
async-trait = "0.1.53"
futures = "0.3"
indexmap = "1.8"
lru = "0.7"
metrics = "0.18"
prost = "0.10"
rand = "0.8"
svix-ksuid = "0.6"
thiserror = "1"
tokio = {version = "1.18", features = ["full"]}
tokio-stream = "0.1.8"
tonic = "0.7"
tower = "0.4"
tracing = "0.1"
trust-dns-resolver = "0.21"

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
tonic-build = "0.7"