[package]
name = "hyparview"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.53"
thiserror = "1"
futures = "0.3"
tokio = {version = "1.18", features = ["full"]}
tokio-stream = "0.1.8"
tracing = "0.1"
indexmap = "1.8"
svix-ksuid = "0.6"
rand = "0.8"
tonic = "0.7"
tower = "0.4"
prost = "0.10"

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
tonic-build = "0.7"