[package]
name = "hyparview"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
crossbeam-channel = "0.4"
fern = "0.6"
indexmap = "1.6.0"
log = "0.4"
parking_lot = "0.11"
rand = "0.7"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "message_store"
harness = false

[profile.bench]
debug = true