[package]
name = "hyparview"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.52"
thiserror = "1"
futures = "0.3"
tokio = {version = "1.17", features = ["full"]}
tracing = "0.1"
indexmap = "1.7"
svix-ksuid = "0.6"
log = "0.4"
parking_lot = "0.11"
rand = "0.8"
tonic = "0.7"
tower = "0.4"
prost = "0.10"

[dev-dependencies]
tracing-subscriber = "0.3"

[build-dependencies]
tonic-build = "0.7"